version: 1.0.{build}
image: Visual Studio 2015
platform:
- Win32
- x64
configuration:
- Release

before_build:
- ps: >-
    If ($env:APPVEYOR_BUILD_VERSION -Like "1.0*") {
      echo  $env:APPVEYOR_BUILD_VERSION
      $current_tag = git describe --tags --long --dirty
      echo  $current_tag
      appveyor UpdateBuild -Version $current_tag
    }
build:
  project: Project64.sln
  parallel: true
  verbosity: minimal
after_build:
- Source/Script/package_zip.cmd %current_tag%-%platform%.zip %platform%

artifacts:
- path: Package/*.zip