image: Visual Studio 2015
build:
  project: Project64.sln
  parallel: true
  verbosity: minimal
platform:
- Win32
- x64
configuration:
- Release

before_build:
- for /f "tokens=1 delims=" %%a in ('git describe --tags --long --dirty') do set current_tag=%%a
- appveyor UpdateBuild -Version %current_tag%

after_build:
- Source/Script/package_zip.cmd %current_tag%-%platform%.zip %platform%

artifacts:
- path: Package/*.zip